import mysql.connector as c
#Admin and login Module
#_main_#
print()
print(" \t\t\t\t WELCOME TO THE MOTI MAHAL HOTELS ")
print(" \t\t\t\t--------------------------------- ")
while True:
    print(" Are you : ")
    print(" 1. A Customer ")
    print(" 2. An administrator ")
    print(" 3. A staff ")
    print(" 4. About ")
    print(" 5. Exit the HOTEL DEEPA COMFORTS page ")
    choice=int(input(" Enter your choice(1,2,3,4 or 5) : "))
    if choice==1:
        print()
        print("---------------------------------------------------")
        print("                  CUSTOMER PAGE                    ")
        print("---------------------------------------------------")
        print(" Dear Customer! Welcome to the HOTEL DEEPA COMFORTS! ")
        print(" Kindly register into our page to buy packages ")
        ch=input(" Do you want to continue with the registration (yes/no) : ")
        if ch[0].lower()=='y':
            registration_details() #Calling of function
            print(" \n\n\n\n ")
            input(" Press any key to continue .......... ")
            print()
            room_selection()       #Calling of function
            input(" Press any key to continue ........... ")
            print()
            print(" Your registration and the required type of room has been successfully reserved for you ")
            print(" You may now start with exploring and availing the facilities in our hotel ")
            print()
            input(" Press any key to continue ........... ")
            print()
            meals_cost=0
            while True:
                print(" Which of the following services you would like to avail... ")
                print(" 1. Order food ")
                print(" 2. Exit ")
                ch2=int(input(" Your choice(1 or 2) : "))
                if ch2==1:
                    print(" ---------------------------------------------------- ")
                    print("                   FOOD ORDERS                        ")
                    print(" ---------------------------------------------------- ")
                    meals()        #Calling of function
                    print()
                    input(" Press any key to continue ........... ")
                    print()
                elif ch2==2:
                    print(" Exiting .......... ")
                    break
                    input(" Press any key to continue ........... ")
                    print()
                else:
                    print(" Invalid choice ")
                    input(" Press any key to continue ........... ")
                    print()
            print()
            print(" Thank you for chosing our services! You may now proceed for the billing ")
            input(" Press any key to continue ........... ")
            print()
            print(" ------------------------------------------------------ ")
            print("                      BILL                              ")
            print(" ------------------------------------------------------ ")
            bill()   #Calling of function
            print()
            print(" We hope to see you again ")
            print(" \n\n\n\n ")
            input(" Press any key to continue ......... ")
        else:
            print(" Thank you for visiting our page! We hope to provide you services in the future ")
            input(" Press any key to continue ......... ")
    elif choice==2:
        #Administrator module
        print(" -------------------------------------------------- ")
        print("                 ADMINISTRATOR PAGE                 ")
        print(" -------------------------------------------------- ")
        print(" LOGIN ")
        user=input(" Enter Admin username : ")
        password=input(" Enter Admin password : ")
        try:
            db=c.connect(host="localhost",user= user,password= password,database="HOTEL_DEEPA_COMFORTS")
            mc=db.cursor()
            while True:
                print("What operations would you like to perform ? ")
                print(" 1. Modify customer details as per their requirement ")
                print(" 2. Overviewing the customer's bill ")
                print(" 3. Overviewing the staff details ")
                print(" 4. Modifying the staff details ")
                print(" 5. Delete a staff record ")
                print(" 6. Delete a customer record ")
                print(" 7. Exit ")
                ch=int(input(" Enter your choice(1,2,3,4,5,6 or 7) : "))
                if ch==1:
                    print()
                    print(" \t\t\t CUSTOMER DATA MODIFICATION ")
                    print()
                    try:
                        #Updation of registration details
                        reg_no=int(input(" Enter the registration number of the customer whose details are to be modified : "))
                        print(" Kindly enter the new or modified details of the customer ")
                        fname=input(" First name : ")
                        sd1="UPDATE REGISTRATION_DETAILS SET FNAME='{}' WHERE REG_NO={}".format(fname,reg_no)
                        mc.execute(sd1)
                        db.commit()
                        lname=input(" Last name : ")
                        sd2="UPDATE REGISTRATION_DETAILS SET LNAME='{}' WHERE REG_NO={}".format(lname,reg_no)
                        mc.execute(sd2)
                        db.commit()
                        citz=input(" Citizenship : ")
                        sd3="UPDATE REGISTRATION_DETAILS SET CITIZENSHIP='{}' WHERE REG_NO={}".format(citz,reg_no)
                        mc.execute(sd3)
                        db.commit()
                        natid_no=input(" National ID card number : ")
                        sd4="UPDATE REGISTRATION_DETAILS SET NATIONAL_IDNO='{}' WHERE REG_NO={}".format(natid_no,reg_no)
                        mc.execute(sd4)
                        db.commit()
                        gender=input(" Gender(M/F) : ")
                        sd5="UPDATE REGISTRATION_DETAILS SET GENDER='{}' WHERE REG_NO={}".format(gender,reg_no)
                        mc.execute(sd5)
                        db.commit()
                        ph_no=int(input(" Phone number : "))
                        sd6="UPDATE REGISTRATION_DETAILS SET PHONE_NO='{}' WHERE REG_NO={}".format(ph_no,reg_no)
                        mc.execute(sd6)
                        db.commit()
                        address=input(" Residential address : ")
                        sd7="UPDATE REGISTRATION_DETAILS SET ADDRESS='{}' WHERE REG_NO={}".format(address,reg_no)
                        mc.execute(sd7)
                        db.commit()
                        email=input(" Email ID : ")
                        sd8="UPDATE REGISTRATION_DETAILS SET EMAIL_ID='{}' WHERE REG_NO={}".format(email,reg_no)
                        mc.execute(sd8)
                        db.commit()
                        nm=int(input(" No.of members : "))
                        sd9="UPDATE REGISTRATION_DETAILS SET NO_MEMBERS={} WHERE REG_NO={}".format(nm,reg_no)
                        mc.execute(sd9)
                        db.commit()
                        print()
                        print(" Details have been successfully updated ! ")
                        input(" Press any key to continue ......... ")
                        print()
                    except:
                        print(" An unexpected connection error occured! Kindly try again! ")
                        input(" Press any key to continue ......... ")
                        print()
                elif ch==2:
                    try:
                        print()
                        print(" \t\t\t CUSTOMER BILL OVERVIEW ")
                        print()
                        room_no=int(input(" Enter the room number of the customer whose billing details you want to view : "))
                        print()
                        sd="SELECT*FROM BILL WHERE ROOM_NO={}".format(room_no)
                        mc.execute(sd)
                        data=mc.fetchall()
                        print(" Accommodation     : ",data[0][1])
                        print(" Food              : ",data[0][2])
                        print()                                     #Additional service aur event organazir create table se delete kar dena
                        print(" GST               : ",data[0][3])   #Tabhi GST 3 aur Total 4 pe hoga 
                        print(" Total             : ",data[0][4])
                        print()
                        input(" Press any key to continue ......... ")
                        print()
                    except:
                        print(" An unexpected error occured! Kindly try again! ")
                        print()
                        input(" Press any key to continue ......... ")
                        print()
                elif ch==3:
                    try:
                        print()
                        print(" \t\t\t OVERVIEWING THE STAFF DETAILS ")
                        sno=int(input(" Enter the staff number whose details you want to view : "))
                        sd="SELECT*FROM STAFF WHERE STAFF_NO={}".format(sno)
                        mc.execute(sd)
                        data=a.fetchall()
                        print(" Staff number     : ",data[0][0])
                        print(" Staff name       : ",data[0][1])
                        print(" Mobile number    : ",data[0][2])
                        print(" Gender           : ",data[0][3])
                        print(" Designation      : ",data[0][4])
                        print(" Salary           : ",data[0][5])
                        print(" National ID no.  : ",data[0][6])
                        print(" Email ID         : ",data[0][7])
                        print(" Account number   : ",data[0][8])
                        print()
                        input(" Press any key to continue ......... ")
                        print()
                    except:
                        print(" An unexpected error occured or the staff number not found! Kindly try again! ")
                        print()
                        input(" Press any key to continue ......... ")
                        print()
                elif s==4:
                    try:
                        print()
                        print(" \t\t\t STAFF DATA MODIFICATION ")
                        reg_no=int(input(" Enter the staff number whose details are to be modified : "))
                        print(" Kindly enter the new or modified details of the staff ")
                        name=input(" Staff name : ")
                        sd1="UPDATE STAFF SET NAME='{}' WHERE STAFF_NO={}".format(name,reg_no)
                        mc.execute(sd1)
                        db.commit()
                        mno=int(input(" Mobile number : "))
                        sd2="UPDATE STAFF SET MOBILE_NO={} WHERE STAFF_NO={}".format(mno,reg_no)
                        mc.execute(sd2)
                        db.commit()
                        gender=input(" Gender(M/F) : ")
                        sd3="UPDATE STAFF SET GENDER='{}' WHERE STAFF_NO={}".format(gender,reg_no)
                        mc.execute(sd3)
                        db.commit()
                        desg=input(" Designation : ")
                        sd4="UPDATE STAFF SET DESIGNATION='{}' WHERE STAFF_NO={}".format(desg,reg_no)
                        mc.execute(sd4)
                        db.commit()
                        sal=int(input(" Salary : "))
                        sd5="UPDATE STAFF SET SALARY={} WHERE STAFF_NO={}".format(sal,reg_no)
                        mc.execute(sd5)
                        db.commit()
                        natid_no=input(" National ID card number : ")
                        sd6="UPDATE STAFF SET NATID_NO='{}' WHERE STAFF_NO={}".format(natid_no,reg_no)
                        mc.execute(sd6)
                        db.commit()
                        email=input(" Email ID : ")
                        sd7="UPDATE STAFF SET EMAIL_ID='{}' WHERE STAFF_NO={}".format(email,reg_no)
                        mc.execute(sd7)
                        db.commit()
                        acno=input(" Account number : ")
                        sd8="UPDATE STAFF SET ACC_NO='{}' WHERE STAFF_NO={}".format(acno,reg_no)
                        mc.execute(sd8)
                        db.commit()
                        print()
                        print(" Details have been successfully updated ! ")
                        print()
                        input(" Press any key to continue ......... ")
                        print()
                    except:
                        print(" An unexpected error occured or the record could not be found! Kindly try again! ")
                        print()
                        input(" Press any key to continue ......... ")
                        print()
                elif ch==5:
                    try:
                        print()
                        print(" \t\t\t STAFF DATA RECORD DELETION" )
                        stno=int(input(" Enter staff number whose record you want to delete : "))
                        sd="DELETE FROM STAFF WHERE STAFF_NO={}".format(stno)
                        mc.execute(sd)
                        db.commit()
                        print(" Record of the staff has been deleted successfully ")
                        print()
                        input(" Press any key to continue ......... ")
                        print()
                    except:
                        print(" An unexpected error occured or the record could not be found! Kindly try again! ")
                        print()
                        input(" Press any key to continue ......... ")
                        print()
                elif ch==6:
                    try:
                        print()
                        print(" \t\t\t CUSTOMER DATA RECORD DELETION" )
                        cno=int(input(" Enter registration number whose record you want to delete : "))
                        sd="DELETE FROM REGISTRATION_DETAILS WHERE REG_NO={}".format(cno)
                        mc.execute(sd)
                        db.commit()
                        print(" Record of the customer has been deleted successfully ")
                        print()
                        input(" Press any key to continue ......... ")
                        print()
                    except:
                        print(" An unexpected error occured or the record could not be found! Kindly try again! ")
                        print()
                        input(" Press any key to continue ......... ")
                        print()
                elif ch==7:
                    print()
                    print(" EXITING.......... ")
                    break
                    input(" Press any key to continue ......... ")
            db.close()
        except:
            print(" KINDLY CHECK YOUR USERNAME AND PASSWORD  TRY AGAIN! ")
            input(" Press any key to continue .......... ")
            print()
    elif choice==3:
        print()
        print(" -------------------------------------------------- ")
        print("                    STAFF PAGE                      ")
        print(" -------------------------------------------------- ")
        print(" Thank you for showing interest in joining our community ")
        print()
        staff()
        print()
        input(" Press any key to continue ......... ")
        print()
    elif choice==4:
        print()
        print(" -------------------------------------------------- ")
        print("                  THE CREATORS                      ")
        print(" -------------------------------------------------- ")
        print(" 1. Geddada Nethranand ")
        print(" 2. Balagouda Patil ")
        print(" 3. Deepanshu Sharma")
        print()
        input(" Press any key to continue ........ ")
        print()
    elif ch==5:
        print(" Exiting permanantly from HOME ........ ")
        print()
        break
        input(" Press any key to continue .......... ")
        print()
    else:
        print(" An invalid choice! ")
        print()
        input(" Press any key to continue ........ ")
        print()
